name: Export Game
on:
  push: {}
  pull_request: {}

jobs:
  godot:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: Build
      uses: firebelley/godot-export@v3.0.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/mono/Godot_v3.4.2-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/mono/Godot_v3.4.2-stable_mono_export_templates.tpz
        relative_project_path: ./
        create_release: false
        use_preset_export_path: true
    - name: Upload Linux build
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: build/linux
        if-no-files-found: error
    - name: Upload Windows build
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: build/windows
        if-no-files-found: error
    - name: Upload macOS build
      uses: actions/upload-artifact@v2
      with:
        name: macOS
        path: build/mac
        if-no-files-found: error
